### ISSUE TITLE
Polylint doesn't like HTML comments

### ISSUE THREAD

**Issue by briansturgill** [bendavis78/polylint#1] opened 2015-01-20 23:29 UTC
<!DOCTYPE html>
<html>
  <body>
        
  </body>
</html>

Running polylint on this file, I get:
WARNING: Element "<built-in function Comment>" is not defined

**Comment by bendavis78** [comment] 2015-07-16 20:51
I'm not able to reproduce this in the latest version, perhaps it was fixed with the previous set of changes.

**Closed by bendavis78** 2015-07-16 20:51 UTC
